# Generated by Django 5.2.7 on 2025-12-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Logger name", max_length=100)),
                ("msg", models.TextField(help_text="Log message content")),
                ("filename", models.CharField(help_text="Source filename", max_length=100)),
                ("levelname", models.CharField(help_text="Log level", max_length=100)),
                ("asctime", models.DateTimeField(help_text="Log timestamp")),
            ],
            options={
                "verbose_name": "log",
                "verbose_name_plural": "logs",
            },
        ),
    ]
